transfer_monitor_worker:
  cron: '* * * * *'
  class: 'TransferMonitorWorker'
mixin_message_monitor_worker:
  cron: '* * * * *'
  class: 'MixinMessageMonitorWorker'
mixin_network_snapshot_monitor_worker:
  cron: '* * * * *'
  class: 'MixinNetworkSnapshotMonitorWorker'
sync_currency_price_worker:
  cron: '*/5 * * * *'
  class: 'SyncCurrencyPriceWorker'
