test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Aliyun
  access_key_id: <%= Rails.application.credentials.dig(:aliyun, :access_key_id) %>
  access_key_secret: <%= Rails.application.credentials.dig(:aliyun, :access_key_secret) %>
  bucket: <%= Rails.application.credentials.dig(:aliyun, :bucket) %>
  endpoint: 'https://oss-cn-hongkong.aliyuncs.com'
  mode: 'public'

production:
  service: Aliyun
  access_key_id: <%= Rails.application.credentials.dig(:aliyun, :access_key_id) %>
  access_key_secret: <%= Rails.application.credentials.dig(:aliyun, :access_key_secret) %>
  bucket: <%= Rails.application.credentials.dig(:aliyun, :bucket) %>
  endpoint: 'https://oss-cn-hongkong.aliyuncs.com'
  mode: 'public'
